### ISSUE TITLE
invalid move is not caught and leads to a dump

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [Ennowulff/axage#11]
Testing @jung-thomas [axage_example](https://github.com/jung-thomas/axage_example) on HANA1909 ( shhh, don't tell SAP ;) )
axage and abap2ui5 are up to date.

Sequence:
N, execute
E, execute

dump in ZCL_AXAGE_ENGINE, method CMD_LOOK
player->location is initial
and this fails:
`IF player->location->things
`

This may or may not have something to do with the fact that N was not an allowable exit in the first move ;)
![image](https://user-images.githubusercontent.com/25269970/236632839-662e1969-f5c1-4bc3-b93f-76898e1d54f4.png)

At the first step, in method INTERPRETE, this comparison fails:
`IF player->location->north = zcl_axage_room=>no_exit.`
During initialization of "entrance", N is correctly marked "no exit" but the objects are different:
![image](https://user-images.githubusercontent.com/25269970/236634157-e4d4229b-2580-4674-a7e0-c94253d86e74.png)

**Comment by jung-thomas** [comment]
Fixed via PR #12 

The serialization of the classes in the stateless version means that object instance ids no longer match exactly. Therefore, the check to no_exit instance of room will always fail.  Changed to checking against the room name instead.

**Comment by Ennowulff** [comment]
thanks

**Comment by AndreaBorgia-Abo** [comment]
> The serialization of the classes in the stateless version means that object instance ids no longer match exactly.

Suspected as much, thanks for the confirmation and for the fix as well :)
