### ISSUE TITLE
Type "IF_OO_ADT_CLASSRUN_OUT" is unknown.

### ISSUE THREAD

**Issue by Ennowulff** [Ennowulff/axage#7]
```ABAP
CLASS zcl_axage_demo1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
    METHODS constructor.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA bill_developer TYPE REF TO zcl_axage_actor.
    DATA mark_consultant TYPE REF TO zcl_axage_actor.
    DATA engine TYPE REF TO zcl_axage_engine.
    METHODS interprete
      IMPORTING
        command TYPE clike
        out     TYPE REF TO if_oo_adt_classrun_out. "<===
ENDCLASS.
```
@jung-thomas is it only available in a cloud system?

**Comment by jung-thomas** [comment]
Definitely not just cloud systems. This is part of normal operations from ABAP Development Tools.  The documentation I have access to says available in all releases 7.52 and higher (actually the interface itself might be available in 7.51 as well according to a note at the end of a blog post from Horst). 

https://blogs.sap.com/2017/12/19/abap-console-output-in-adt/

**Comment by Ennowulff** [comment]
I don't even dare to ask, but may be you mixed up with IF_OO_ADT_CLASSRUN (w/o "OUT")?

**Comment by jung-thomas** [comment]
The out object is part of that. It's the writer object passed in the main method. I'm just passing the writer around to make things cleaner in the code.  Are you saying you have the classrun interface itself but not the output writer in your release?

**Comment by Ennowulff** [comment]
> Are you saying you have the classrun interface itself but not the output writer in your release?
That's right. Release 750. Maybe one or two points too low...

**Comment by jung-thomas** [comment]
Well then, I'll change that this afternoon. Instead of passing the writer object I'll pass the results data back and keep the writer where it is. Less elegant, but if it provides better release compatibility, that's fine.

**Comment by jung-thomas** [comment]
PR #9 is available and should address this issue.

**Comment by Ennowulff** [comment]
#9
